### ISSUE TITLE
Note calculation

### ISSUE THREAD

**Issue by Firekorn** [Anahkiasen/furnace#16]
Thanks for posting the formula.

First off there's a big issue in the formula. 
You integrate the need for the CDLC to have been updated in the past 6 months. A perfect CDLC should not need any kind of update making his note loose one point after 6 month which makes no sense and that would also lead to a major issue on CustomsForge side which is update spamming to gain the little point.

Second, the use of the number of levels will always lead to misinterpretation, a high number of level only means that the song is complicated and nothing more an easy (even officials) can have less than 16 (even 8 is not always reached by official) levels of difficulty which would make them unable to reach the 20/20 mark.

Thirdly, even official do not always contain up to 4 part and some acoustic or purely instrumental song will be at 2/3 part and still be perfect from a quality point of view yet that would make them unable to reach the 20/20 mark...

Overall i have a bad feeling about the way your formula work because it not only looks for non-important element but also overlook the more important detail that is the FHP definition or the handshape and all little things like that are just packed together in the tab section and count for only 3 point at best while this is the core of the CDLC. Also you completely forget about the beat map and the sync of the song.

It's a really difficult things to evaluate quality of a CDLC but i think the biggest issue i have is that even a perfect songs might not obtain the 20/20 mark because of no quality related element.

On the bright side, sometimes a simple ponderation of some element (tab quality) and some simple question like : does it crash? could be way more important in the quality notation and easily implemented.

**Comment by zerkz** [comment]
@Firekorn its impossible to tell whether or not it will crash with the data provided. I don't think we could ever have an automated process that could figure that out... it would have to be user controlled.

**Comment by Firekorn** [comment]
There's already some user data used on the note calculation (Tone, tab and audio evaluation). Adding other drop down menu to add other kind of information concerning quality could easily be an option.

**Comment by Anahkiasen** [comment]
The rating formula is at a very first draft stage so I expected feedback on it indeed, it was pretty much made as a "starting point" to discuss with the community from.

> You integrate the need for the CDLC to have been updated in the past 6 months. A perfect CDLC should not need any kind of update making his note loose one point after 6 month which makes no sense and that would also lead to a major issue on CustomsForge side which is update spamming to gain the little point.

Hm true, will remove that portion.

> Second, the use of the number of levels will always lead to misinterpretation, a high number of level only means that the song is complicated and nothing more an easy (even officials) can have less than 16 (even 8 is not always reached by official) levels of difficulty which would make them unable to reach the 20/20 mark.

Currently it's done as a ratio compared to the standard number which is 8, so it doesn't affect the rating that much. Having 2 levels of difficulty instead of 8 means you'd only lose 0.75 points while having more is just considered extra points. What I could do is cap to 1, so additional levels don't grant extra points, but I feel it's important to take into account. Songs can have DD and RR but if they only have two levels of difficulty it's not really helping.
I'm not sure however what the "standard" is, I put 8 cause I thought I had read somewhere that was what the default was in Editor on Fire but can you confirm this?

> Overall i have a bad feeling about the way your formula work because it not only looks for non-important element but also overlook the more important detail that is the FHP definition or the handshape and all little things like that are just packed together in the tab section and count for only 3 point at best while this is the core of the CDLC. Also you completely forget about the beat map and the sync of the song.

Hm yeah true. What if I split the "tab" part into sections:
- Is the tablature in sync with the song?
- Is the tablature correct?
- Are the techniques properly used (that would encapsulate handshapes)

The reason I had made the criteras so brief was to not "turn off" people, like if they have 50 things they have to pay attention to and fill in, but at the same time having representative ratings is more important so.

> On the bright side, sometimes a simple ponderation of some element (tab quality) and some simple question like : does it crash? could be way more important in the quality notation and easily implemented.

That's already in the form, but maybe it's not explained correctly, that's the "Is it playable?" field. Crashes would go in that. That is also the reason I ask the plateform to the user, so it can be shown if the track crashes on a certain plateform but not on another.

**Comment by Anahkiasen** [comment]
Do keep in mind the 20 mark is absolutely arbitrary, it's just the some of all the criterias we have now. If I remove the updated at critera it becomes 19. I should maybe put that into % so it doesn't change all the time

**Comment by Anahkiasen** [comment]
> Thirdly, even official do not always contain up to 4 part and some acoustic or purely instrumental song will be at 2/3 part and still be perfect from a quality point of view yet that would make them unable to reach the 20/20 mark...

Hm yeah correct too. It's too bad there's not a way to assert how many parts there is compared to how many parts there _should be_. I really wanted to reward the work of packing alternate leads and bass tracks and vocals when appropriate.

I think a solution to most these issues would be to apply weight to these criterias instead of all merging them as having the same importance, no?

**Comment by Firekorn** [comment]
>I'm not sure however what the "standard" is, I put 8 cause I thought I had read somewhere that was what the default was in Editor on Fire but can you confirm this?
So far, i'm not sure many charter use EOF for DD creation but mostly DDC made by chlipouni (https://ddcreator.wordpress.com/) which integrate a function to keep to 5 or 8 levels of difficulty so 5 seems like a more appropriate minimum requirement than 8.

>The reason I had made the criteria so brief was to not "turn off" people
It's true that having too many question could throw some people off but too little might mess up the end result which is not something that anybody would want...

>That's already in the form, but maybe it's not explained correctly, that's the "Is it playable?" field. Crashes would go in that. That is also the reason I ask the platform to the user, so it can be shown if the track crashes on a certain platform but not on another.
Well my mind just skipped that question but if it's there i have nothing more to say :)

>Do keep in mind the 20 mark is absolutely arbitrary, it's just the sum of all the criterias we have now. If I remove the updated at critera it becomes 19. I should maybe put that into % so it doesn't change all the time
The maximum doesn't really matter but it has to obtainable. I've used it to point out that it wasn't always even if the cdlc is perfect in every way possible.

>I think a solution to most these issues would be to apply weight to these criterias instead of all merging them as having the same importance, no?
Vocals is always less important since it's just for the look but won't change the fundamental quality of the cdlc so making it less important than the others could help. On this point i would send back to what i said just before. You need to be able to obtain the maximum rating if it's perfect, meaning that a bass only cdlc (for exemple) should be able to obtain it or at least be really close so that the missing (that aren't really missing) don't make the rating fall drastically.
If there is one part playable, it's most of the job (like 75% of the "parts" rating) the second one will get the rating up to 90% and the last part will get to 99 and vocals add that little extra % for example.

**Comment by Anahkiasen** [comment]
I'm gonna remove the "parts" part of the formula, I'll try to think of a fairer way to integrate it but right now they all rely on data I don't have so, doesn't matter.

So that boils it down to these components for the score formula:

```php
    'weights'    => [
        'tone'              => 1,
        'audio'             => 1,
        'tab'               => 1,
        'normalized_volume' => 1,
        'presilence'        => 1,
        'dd'                => 1,
        'rr'                => 1,
        'difficulty_levels' => 1,
    ],
```

They currently all have a weight of one, hardest part is not to reweight those accordingly. Keeping in mind this doesn't yet have the additional extra "tab" criterias yet, need to see how to integrate those gracefully.
